### ISSUE TITLE
Can't create a new recipe version

### ISSUE THREAD

**Issue by olivierkastel** [papinette/issues#1]
From the recipe view (https://app.papinette.com/recipes/22/versions/last) when I click on the New version button, the page is blank and I have the following error in the console :

<img width="1177" alt="api" src="https://user-images.githubusercontent.com/13841209/65757021-8b0e2180-e116-11e9-9863-8cb820d76d29.png">

No API error though.

**Comment by hourliert** [comment]
This has been fixed in https://github.com/hourliert/my-recipe-box-app/pull/131.

The step input looks a bit weird with the fix but I'll address it later in another PR.
